steps:
  #
  # Deploy to Cloud Run
  #
  # 1. build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/putongwords/putongwords", "."]

    # 2. push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/putongwords/putongwords"]

    # 3. Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "putongwords",
        "--image",
        "gcr.io/putongwords/putongwords",
        "--region",
        "us-east1",
        "--platform",
        "managed",
        "--quiet",
      ]

images:
  - gcr.io/putongwords/putongwords
